### ISSUE TITLE
Warnings during build on alpine

### ISSUE THREAD

**Issue by waldner** [backuppc/rsync-bpc#11]
Building rsync_bpc under alpine linux, many warnings are emitted, although the compilation finally succeeds. See the attached file: 
[warnings.txt](https://github.com/backuppc/rsync-bpc/files/3172373/warnings.txt)

**Comment by craigbarratt** [comment]
Most of these should be fixed in the latest releases.

**Comment by waldner** [comment]
I'm still seeing those wirh rsync-bpc 3.1.2.2. Do you mean with 3.1.3 beta?

**Comment by craigbarratt** [comment]
Yes.  I should release 3.1.3.0 shortly, which only has a couple of minor changes from 3.1.3beta1.

**Comment by waldner** [comment]
With 3.1.3.0 only the following warnings are produced:

```
gcc -I. -I. -I./zlib -I./popt -g -O2 -DHAVE_CONFIG_H -Wall -W  -c socket.c -o socket.o
socket.c: In function 'open_socket_out':
socket.c:76:59: warning: '%s' directive output may be truncated writing up to 1023 bytes into a region of size between 976 and 1005 [-Wformat-truncation=]
   76 |  snprintf(buffer, sizeof buffer, "CONNECT %s:%d HTTP/1.0%s%s\r\n\r\n",
      |                                                           ^~
   77 |    host, port, authhdr, authbuf);
      |                         ~~~~~~~                            
socket.c:76:2: note: 'snprintf' output 24 or more bytes (assuming 1076) into a destination of size 1024
   76 |  snprintf(buffer, sizeof buffer, "CONNECT %s:%d HTTP/1.0%s%s\r\n\r\n",
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   77 |    host, port, authhdr, authbuf);
      |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
gcc -I. -I. -I./zlib -I./popt -g -O2 -DHAVE_CONFIG_H -Wall -W  -c popt/popt.c -o popt/popt.o
popt/popt.c: In function 'expandNextArg':
popt/popt.c:629:6: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  629 |      strncpy(te, a, alen); te += alen;
      |      ^~~~~~~~~~~~~~~~~~~~
popt/popt.c:624:13: note: length computed here
  624 |      alen = strlen(a);
      |             ^~~~~~~~~

```

**Comment by GWHAYWOOD** [comment]
Closing this issue as the latest version of rsync-bpc (3.4.1.0rc1) compiles (at least here:) with no warnings.

Please see issue #44 for more details.
